[package]
name = "wpilog-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bimap = "0.6.3"
serde = { version = "^1", features = ["derive"] }
thiserror = "1.0.40"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"


[features]
tracing = []

[profile.release]
lto = true
